### ISSUE TITLE
RSS Feeds broken

### ISSUE THREAD

**Issue by LordHelmchen666** [JoomCoder-com/JoomCCK#180]
When i turn on RSS Feeds they are not shown.
Links are shown in source code
```
<link href="/rezepte/rezepte?format=feed&amp;type=rss" rel="alternate" type="application/rss+xml" title="RSS 2.0">
<link href="/rezepte/rezepte?format=feed&amp;type=atom" rel="alternate" type="application/atom+xml" title="Atom 1.0">
```
But when i click only blank page visible. When i view source code there is only '1' shown.

**Comment by andiamine** [comment]
Fixed 
thanks for reporting this issue

**Comment by Giorgi625** [comment]
Oh finally you are back, I was just writing very negative post in Joomla extensions group for you, man please be responsible for your job and do not disappear like this. We did not purchase your extensions to have fun, but to work and get some income. and disapearing for so long time is not acceptable. If you plan to continue this way then will be better if you giveaway this extension to someone responsible.

**Comment by andiamine** [comment]
> Oh finally you are back, I was just writing very negative post in Joomla extensions group for you, man please be responsible for your job and do not disappear like this. We did not purchase your extensions to have fun, but to work and get some income. and disapearing for so long time is not acceptable. If you plan to continue this way then will be better if you giveaway this extension to someone responsible.

I was very sick.

**Comment by Giorgi625** [comment]
Do you work alone, you multiple times have mentioned team, you can ask someone from your team to take care of it or at least let us know there is something with you. You were sick also when I first reported about slow support. So what we should do if you get sick often? wait for whole month until you get better?

**Comment by andiamine** [comment]
we do apologize team with already busy without me with other products last month.

**Comment by Giorgi625** [comment]
I understand we are all humans, but do not think it would be a big deal for someone to come and let us know what's happening. You know very well what we have been through. When I purchased Cobalt's Lifetime Subscription I was assured that it will at least be released for J4 and Sergey was working on it but we never got to it so he dumped us and let to Vasiliy regular Russian Nazi, who assured that he will do job, but did not do anything for months. Then finally You came and did the job, it took quite long but its understandable cause there were not many testers. But at least when you get paid for product you should take responsibility to at least notify your clients if there is any problems, You do not understand how much loss I get because JoomCCK is not yet fully stable.

**Comment by andiamine** [comment]
@Giorgi625 we do understand your concern, we are still a small team, and looking forward to make JoomCCK better product with clients like you, currently JoomCCK still not yet published on JED, we didn't get many purchases yet, but with your support JoomCCK will be better in future.

**Comment by Giorgi625** [comment]
Great, also will be good if you can guide me what I should learn to be able to fix stuff in JoomCCK?
